(() => {
  'use strict';
  const OWNER='carloskk07', REPO='shopee', SITE='https://achadostube.com.br', API=`https://api.github.com/repos/${OWNER}/${REPO}`;
  const READ_HEADERS={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
  const state={token:null,user:null,view:'today',repo:null,siteData:null,monetization:null,release:null,prodRelease:null,commits:[],pulls:[],runs:[],tree:[],staged:new Map(),gsc:null,selectedFile:null};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n||0));
  const pct=n=>`${Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`;
  const date=v=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
  const short=s=>String(s||'').slice(0,8);
  const toast=(msg,kind='good')=>{const t=$('#toast');t.textContent=msg;t.className=`toast show ${kind}`;clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',3200)};
  const ghHeaders=()=>({...READ_HEADERS,...(state.token?{'Authorization':`Bearer ${state.token}`}:{})});
  async function request(url,opts={}){const r=await fetch(url,{...opts,headers:{...ghHeaders(),...(opts.headers||{})}});if(!r.ok){let msg=`${r.status} ${r.statusText}`;try{const j=await r.json();msg=j.message||msg}catch(_){}throw new Error(msg)}return r.status===204?null:r.json()}
  async function textRequest(url){const r=await fetch(url,{headers:ghHeaders(),cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
  async function ghFile(path,ref='main'){const j=await request(`${API}/contents/${encodePath(path)}?ref=${encodeURIComponent(ref)}`);if(j.type!=='file')throw new Error('Não é um arquivo');return {text:decode64(j.content),sha:j.sha,size:j.size,path:j.path}}
  const encodePath=p=>p.split('/').map(encodeURIComponent).join('/');
  const decode64=s=>new TextDecoder().decode(Uint8Array.from(atob(String(s).replace(/\n/g,'')),c=>c.charCodeAt(0)));
  const toB64=s=>{const bytes=new TextEncoder().encode(s);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)};
  async function sha256(s){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  function stage(path,content,label=path){state.staged.set(path,{path,content,label});updateStaged();toast(`${label} adicionado ao change set`)}
  function unstage(path){state.staged.delete(path);updateStaged();render()}
  function updateStaged(){const n=state.staged.size;$('#stagedBadge').textContent=n;$('#publishBtn').disabled=!state.token||!n}
  const viewNames={today:'Hoje',books:'Livros',guides:'Guias',seo:'SEO & GSC',money:'Monetização',releases:'Releases',quality:'Qualidade',editor:'Editor seguro',settings:'Configurações'};
  function setView(v){state.view=v;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#viewTitle').textContent=viewNames[v]||v;$('.sidebar').classList.remove('open');render()}
  function pill(text,kind=''){return `<span class="pill ${kind}">${esc(text)}</span>`}
  function metric(label,value,detail='',kind=''){return `<div class="card metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small class="delta ${kind}">${esc(detail)}</small></div>`}
  function card(title,body,subtitle=''){return `<section class="card pad"><div class="card-header"><div><h3>${esc(title)}</h3>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div></div>${body}</section>`}
  function gscStats(){const rows=state.gsc?.rows||[];const clicks=rows.reduce((a,r)=>a+(+r.clicks||0),0),imp=rows.reduce((a,r)=>a+(+r.impressions||0),0);const ctr=imp?clicks/imp*100:0;const posDen=rows.reduce((a,r)=>a+(+r.impressions||0),0);const pos=posDen?rows.reduce((a,r)=>a+(+r.position||0)*(+r.impressions||0),0)/posDen:0;return {clicks,imp,ctr,pos}}
  async function loadAll(){
    $('#envLabel').textContent='Atualizando…';$('#envDot').className='';
    const safe=async(fn,fallback)=>{try{return await fn()}catch(e){console.warn(e);return fallback}};
    const [repo,sd,mon,rel,prod,commits,pulls,runs,tree]=await Promise.all([
      safe(()=>request(API),state.repo),safe(()=>ghFile('site-data.generated.json').then(x=>JSON.parse(x.text)),state.siteData),safe(()=>ghFile('monetization.json').then(x=>JSON.parse(x.text)),state.monetization),safe(()=>ghFile('release.json').then(x=>JSON.parse(x.text)),state.release),safe(()=>fetch(`${SITE}/release.json?admin=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),state.prodRelease),safe(()=>request(`${API}/commits?per_page=12`),[]),safe(()=>request(`${API}/pulls?state=open&per_page=12`),[]),safe(()=>request(`${API}/actions/runs?per_page=20`).then(x=>x.workflow_runs||[]),[]),safe(()=>request(`${API}/git/trees/main?recursive=1`).then(x=>x.tree||[]),[])
    ]);
    Object.assign(state,{repo,siteData:sd,monetization:mon,release:rel,prodRelease:prod,commits,pulls,runs,tree});
    const exact=rel&&prod&&JSON.stringify(rel)===JSON.stringify(prod);$('#envDot').className=exact?'good':'bad';$('#envLabel').textContent=exact?'Produção sincronizada':'Verificar produção';
    try{const cached=sessionStorage.getItem('freedom-gsc-v1');if(cached&&!state.gsc)state.gsc=JSON.parse(cached)}catch(_){}
    render();
  }
  function todayView(){const s=gscStats();const latest=state.runs[0];const failed=state.runs.filter(r=>r.status==='completed'&&r.conclusion!=='success').length;const open=state.pulls.length;const exact=state.release&&state.prodRelease&&JSON.stringify(state.release)===JSON.stringify(state.prodRelease);const books=state.siteData?.books||[], guides=state.siteData?.guides||[];const actions=[];
    if(!exact)actions.push(['P0','Release de produção diverge do repositório','Verifique deploy antes de qualquer edição.']);
    if(failed)actions.push(['P0',`${failed} workflow(s) recente(s) fora de success`,'Abrir Releases e diagnosticar antes de publicar.']);
    if(!state.gsc)actions.push(['P1','Importar dados recentes do Search Console','O módulo SEO usa o CSV localmente e não envia dados a terceiros.']);
    if(state.monetization?.affiliates?.enabled===false)actions.push(['P2','Afiliados preparados, ainda inativos','Ative somente quando houver URL afiliada real e contextual.']);
    if(!actions.length)actions.push(['OK','Nenhum bloqueio operacional detectado','Preserve estabilidade e trabalhe apenas na próxima oportunidade com evidência.']);
    return `<div class="stack">
      <div class="hero-grid"><section class="card hero-status"><div><span class="kicker">Estado operacional</span><h2>${exact?'Site publicado e contrato de release sincronizado.':'Há uma divergência que merece atenção antes da próxima publicação.'}</h2><p>O painel prioriza integridade, SEO com evidência e monetização sem degradar a experiência editorial.</p></div><div class="status-row">${pill(`main ${short(state.commits[0]?.sha)}`,exact?'good':'warn')}${pill(`${books.filter(b=>b.available).length} livros ativos`)}${pill(`${guides.length} guias`)}${pill(`${open} PR aberto${open===1?'':'s'}`,open?'warn':'good')}</div></section>
      <section class="card pad"><div class="card-header"><div><span class="kicker">Fila inteligente</span><h3>O que merece atenção</h3></div></div><div class="action-list">${actions.slice(0,5).map((a,i)=>`<div class="action-item"><div class="rank">${esc(a[0])}</div><div><strong>${esc(a[1])}</strong><small>${esc(a[2])}</small></div></div>`).join('')}</div></section></div>
      <div class="metric-grid">${metric('Impressões GSC',state.gsc?fmt(s.imp):'—',state.gsc?'último CSV importado':'sem dados')}${metric('CTR GSC',state.gsc?pct(s.ctr):'—',state.gsc?'ponderado por impressões':'importe um CSV')}${metric('Posição média',state.gsc?s.pos.toFixed(1).replace('.',','):'—',state.gsc?'consulta/página importada':'sem dados')}${metric('Deploy recente',latest?.conclusion||latest?.status||'—',latest?latest.name:'sem histórico',latest?.conclusion==='success'?'good':latest?'warn':'')}</div>
      <div class="split">${recentRuns()}${recentPrs()}</div>
    </div>`}
  function recentRuns(){const rows=state.runs.slice(0,8).map(r=>`<tr><td><strong>${esc(r.name)}</strong><br><small>${esc(r.display_title||'')}</small></td><td>${pill(r.conclusion||r.status,r.conclusion==='success'?'good':r.conclusion?'bad':'warn')}</td><td class="mono">${short(r.head_sha)}</td><td>${date(r.updated_at||r.created_at)}</td></tr>`).join('');return card('Pipelines recentes',`<div class="table-wrap"><table><thead><tr><th>Workflow</th><th>Estado</th><th>Commit</th><th>Atualizado</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Sem dados</td></tr>'}</tbody></table></div>`,'GitHub Actions')}
  function recentPrs(){const rows=state.pulls.slice(0,8).map(p=>`<tr><td><strong>#${p.number} ${esc(p.title)}</strong></td><td>${pill(p.draft?'draft':'open',p.draft?'warn':'good')}</td><td class="mono">${short(p.head?.sha)}</td><td><a class="link-btn" href="${esc(p.html_url)}" target="_blank" rel="noopener">Abrir</a></td></tr>`).join('');return card('Pull Requests',`<div class="table-wrap"><table><thead><tr><th>PR</th><th>Estado</th><th>Head</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="4">Nenhum PR aberto</td></tr>'}</tbody></table></div>`,'Nada publica direto na main')}
  function booksView(){const books=state.siteData?.books||[];return `<div class="stack">${sectionIntro('Catálogo editorial','Gerencie o catálogo sem perder a verdade do PDF, capa, landing e disponibilidade.')}<section class="card pad"><div class="toolbar"><input id="bookSearch" class="search" placeholder="Buscar livro…"><span>${fmt(books.length)} registros · ${fmt(books.filter(b=>b.available).length)} publicados</span></div><div class="table-wrap"><table><thead><tr><th>Livro</th><th>Status</th><th>Temas</th><th>PDF</th><th>Ações</th></tr></thead><tbody id="booksBody">${booksRows(books)}</tbody></table></div></section></div>`}
  function booksRows(books){return books.map(b=>`<tr><td><div class="title-cell"><img class="cover" src="${esc(b.cover||'/assets/covers/logo-freedom-book-redonda.webp')}" alt=""><div><strong>${esc(b.title)}</strong><small>${esc(b.slug)}</small></div></div></td><td>${pill(b.available?'Publicado':'Planejado',b.available?'good':'warn')}</td><td>${esc((b.tags||b.themes||[]).slice(0,3).join(' · ')||'—')}</td><td>${b.pdfUrl?'<span class="pill good">PDF</span>':'—'}</td><td><div class="small-actions"><button class="mini-btn" data-open-site="${esc(b.pageUrl||`${SITE}/${b.slug}`)}">Ver</button><button class="mini-btn" data-edit-file="site-data.generated.json">Editar dados</button>${b.available?`<button class="mini-btn" data-edit-file="${esc(b.slug)}.html">Editar landing</button>`:''}</div></td></tr>`).join('')}
  function guidesView(){const gs=state.siteData?.guides||[];return `<div class="stack">${sectionIntro('Guias & autoridade temática','Conteúdo original com controle de links, autoria e integridade editorial.')}<section class="card pad"><div class="table-wrap"><table><thead><tr><th>Guia</th><th>URL</th><th>Relação</th><th>Ações</th></tr></thead><tbody>${gs.map(g=>{const path=new URL(g.url).pathname.replace(/^\//,'')+'.html';return `<tr><td><strong>${esc(g.title)}</strong><br><small>${esc(g.description||'')}</small></td><td class="mono">${esc(new URL(g.url).pathname)}</td><td>${esc((g.tags||g.themes||[]).slice(0,3).join(' · ')||'Editorial')}</td><td><div class="small-actions"><button class="mini-btn" data-open-site="${esc(g.url)}">Ver</button><button class="mini-btn" data-edit-file="${esc(path)}">Editar</button></div></td></tr>`}).join('')}</tbody></table></div></section></div>`}
  function sectionIntro(title,text){return `<section class="card pad"><div class="card-header"><div><span class="kicker">Control plane</span><h2>${esc(title)}</h2><p>${esc(text)}</p></div></div></section>`}
  function seoView(){const s=gscStats();const rows=(state.gsc?.rows||[]).slice().sort((a,b)=>(+b.impressions||0)-(+a.impressions||0)).slice(0,30);return `<div class="stack">${sectionIntro('SEO Intelligence','Search Console é tratado como evidência: não criamos páginas ou alteramos SEO só para preencher o painel.')}<div class="metric-grid">${metric('Cliques',state.gsc?fmt(s.clicks):'—')}${metric('Impressões',state.gsc?fmt(s.imp):'—')}${metric('CTR',state.gsc?pct(s.ctr):'—')}${metric('Posição',state.gsc?s.pos.toFixed(1).replace('.',','):'—')}</div><section class="card pad"><div class="toolbar"><div><strong>Dados Search Console</strong><div style="color:var(--muted);font-size:12px">Importação local. O CSV fica nesta sessão do navegador.</div></div><label class="btn secondary" style="margin:0;display:inline-block">Importar CSV<input id="gscFile" type="file" accept=".csv,text/csv" hidden></label></div>${state.gsc?`<div class="table-wrap"><table><thead><tr><th>Consulta / dimensão</th><th>Cliques</th><th>Impressões</th><th>CTR</th><th>Posição</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.query||r.page||r.key||'—')}</strong></td><td>${fmt(r.clicks)}</td><td>${fmt(r.impressions)}</td><td>${pct(r.ctr)}</td><td>${Number(r.position||0).toFixed(1).replace('.',',')}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Importe um CSV exportado do Search Console para ativar análise local neste painel.</div>`}</section>${seoOpportunities(rows)}</div>`}
  function seoOpportunities(rows){if(!rows.length)return '';const opp=rows.map(r=>{const imp=+r.impressions||0,pos=+r.position||0,ctr=+r.ctr||0;if(imp>=30&&pos<=10&&ctr<2)return ['CTR_OPPORTUNITY',r,'Melhorar snippet/intent da página existente.'];if(imp>=20&&pos>=8&&pos<=20)return ['STRIKING_DISTANCE',r,'Prioridade alta: trabalhar página existente antes de criar URL.'];return null}).filter(Boolean).slice(0,8);return card('Oportunidades orientadas por evidência',opp.length?`<div class="action-list">${opp.map((o,i)=>`<div class="action-item"><div class="rank">${i+1}</div><div><strong>${esc(o[0])}: ${esc(o[1].query||o[1].page||o[1].key)}</strong><small>${esc(o[2])} · ${fmt(o[1].impressions)} imp · pos ${Number(o[1].position).toFixed(1)}</small></div></div>`).join('')}</div>`:'<div class="empty">Nenhuma oportunidade ultrapassou os thresholds mínimos neste arquivo.</div>')}
  function moneyView(){const m=state.monetization||{};const aff=m.affiliates||{}, prem=m.premium||{}, sup=m.support||{};return `<div class="stack">${sectionIntro('Monetização nativa','Controle central de apoio, premium e afiliados com guardrails contra degradação editorial.')}<div class="triple">${moneyCard('Apoio LivePix',sup.enabled,'Ativo em páginas elegíveis',sup.url||'')}${moneyCard('Edições premium',prem.enabled,`${(prem.offers||[]).length} oferta(s) configurada(s)`,'Ativar só com produto real')}${moneyCard('Afiliados',aff.enabled,`${(aff.offers||[]).length} oferta(s) configurada(s)`,'Links futuros exigem sponsored')}</div><section class="card pad"><div class="card-header"><div><h3>Configuração central</h3><p>Edite com validação JSON e envie por PR.</p></div><button class="btn secondary" data-edit-file="monetization.json">Abrir no editor seguro</button></div><div class="quality-grid">${guardChecks(m.guardrails||{})}</div></section></div>`}
  function moneyCard(title,on,detail,note){return `<section class="card pad"><div class="card-header"><div><span class="kicker">${on?'Ativo':'Preparado'}</span><h3>${esc(title)}</h3></div>${pill(on?'ON':'OFF',on?'good':'warn')}</div><p>${esc(detail)}</p><small style="color:var(--muted)">${esc(note)}</small></section>`}
  function guardChecks(g){const defs=[['Sem popups',g.noPopups],['Sem interstitials',g.noInterstitials],['Sem scripts terceiros',g.noThirdPartyScripts],['Afiliado contextual',g.recommendOnlyWhenRelevant],['Sponsored obrigatório',g.affiliateRel==='sponsored noopener noreferrer'],['Máximo 2 blocos',+g.maxInjectedBlocksPerPage<=2]];return defs.map(([n,ok])=>`<div class="check ${ok?'':'bad'}"><i>${ok?'✓':'!'}</i><div><strong>${esc(n)}</strong><span>${ok?'Contrato ativo':'Requer correção'}</span></div></div>`).join('')}
  function releasesView(){const exact=state.release&&state.prodRelease&&JSON.stringify(state.release)===JSON.stringify(state.prodRelease);return `<div class="stack">${sectionIntro('Releases & deploy','Acompanhe main, Pages e smoke sem precisar navegar pela interface técnica do GitHub.')}<div class="metric-grid">${metric('Release',state.release?.release||'—',exact?'produção idêntica':'divergência',exact?'good':'bad')}${metric('Main',short(state.commits[0]?.sha)||'—',state.commits[0]?.commit?.message?.split('\n')[0]||'')}${metric('Artefatos',fmt(Object.keys(state.release?.artifacts||{}).length),'com SHA-256')}${metric('PRs abertos',fmt(state.pulls.length),'fluxo protegido',state.pulls.length?'warn':'good')}</div>${recentRuns()}${recentPrs()}</div>`}
  function qualityView(){const checks=[];const books=state.siteData?.books||[], guides=state.siteData?.guides||[], art=state.release?.artifacts||{};checks.push(['Release produção',JSON.stringify(state.release)===JSON.stringify(state.prodRelease),'release.json em produção corresponde à main']);checks.push(['Catálogo',books.length===11,`${books.length} livros registrados`]);checks.push(['Publicados',books.filter(b=>b.available).length===10,`${books.filter(b=>b.available).length} PDFs/livros ativos`]);checks.push(['Guias',guides.length===6,`${guides.length} guias editoriais`]);checks.push(['Monetização',state.monetization?.schema==='freedom-book-monetization-v1','control plane carregado']);checks.push(['Release surface',Object.keys(art).length>=51,`${Object.keys(art).length} artefatos sob hash`]);checks.push(['Admin no sitemap',false,'/admin deve permanecer fora do sitemap e noindex',true]);const failed=state.runs.filter(r=>r.status==='completed'&&r.conclusion!=='success').length;checks.push(['Workflows recentes',failed===0,failed?`${failed} falha(s) encontrada(s)`:'sem falha recente']);return `<div class="stack">${sectionIntro('Quality Gate','Auditoria rápida do estado do site. O CI continua sendo a autoridade final antes de merge.')}<section class="card pad"><div class="quality-grid">${checks.map(([n,ok,d,invert])=>{if(invert)ok=!ok;return `<div class="check ${ok?'':'bad'}"><i>${ok?'✓':'!'}</i><div><strong>${esc(n)}</strong><span>${esc(d)}</span></div></div>`}).join('')}</div></section></div>`}
  function textFiles(){const exts=/\.(html|json|xml|txt|md|js|css|webmanifest)$/i;return state.tree.filter(x=>x.type==='blob'&&exts.test(x.path)&&!x.path.startsWith('.github/workflows/')&&!x.path.startsWith('admin/')&&!x.path.includes('__pycache__')).map(x=>x.path).sort()}
  function editorView(){const files=textFiles();return `<div class="stack">${sectionIntro('Editor seguro','Edite texto no repositório com staging local. A main nunca recebe escrita direta. Workflows e o próprio painel são bloqueados nesta interface.')}<div class="editor-grid"><section class="card file-list"><input id="fileFilter" placeholder="Filtrar arquivo…">${files.map(f=>`<button data-file="${esc(f)}" class="${criticalFile(f)?'critical':''}">${esc(f)}</button>`).join('')}</section><section class="card pad"><div id="editorPane" class="empty">Selecione um arquivo ou use os botões “Editar” nas outras áreas.</div></section></div>${stagedPanel()}</div>`}
  function criticalFile(f){return /^(robots\.txt|sitemap\.xml|release\.json|manifest\.webmanifest|.*\.html)$/.test(f)}
  function stagedPanel(){if(!state.staged.size)return card('Change set','<div class="empty">Nenhuma alteração preparada.</div>','As alterações ficam apenas nesta aba até você criar um PR.');return card('Change set',`<div class="action-list">${[...state.staged.values()].map(x=>`<div class="action-item"><div class="rank">✓</div><div style="flex:1"><strong>${esc(x.label)}</strong><small class="mono">${esc(x.path)}</small></div><button class="mini-btn" data-unstage="${esc(x.path)}">Remover</button></div>`).join('')}</div>`,'Pronto para branch + commit + PR')}
  function settingsView(){return `<div class="stack">${sectionIntro('Configurações','O painel não armazena segredos. Dados não sensíveis do GSC podem sobreviver apenas enquanto esta aba estiver aberta.')}<div class="split">${card('Sessão GitHub',`<p>${state.user?`Conectado como <strong>${esc(state.user.login)}</strong>. O token permanece somente em memória.`:'Modo leitura. Conecte um token fine-grained para criar PRs.'}</p><button id="settingsSession" class="btn ${state.user?'secondary':''}">${state.user?'Encerrar sessão':'Conectar GitHub'}</button>`,'Segredo nunca persistido')}${card('Integrações',`<div class="action-list"><div class="action-item"><div class="rank">G</div><div><strong>Google Search Console</strong><small>Importação CSV local ativa. OAuth direto não configurado neste domínio.</small></div></div><div class="action-item"><div class="rank">$</div><div><strong>Monetização</strong><small>LivePix ativo; premium e afiliados controlados por monetization.json.</small></div></div></div>`,'Conexões explícitas, sem trackers ocultos')}</div><div class="notice"><strong>Segurança atual:</strong> o shell do painel está em GitHub Pages, portanto o HTML é publicamente acessível, embora esteja noindex. Operações de escrita só ficam disponíveis após autenticação GitHub válida. Para isolamento de acesso ao próprio shell, a próxima camada é mover apenas o admin para backend com autenticação server-side.</div></div>`}
  function render(){const v={today:todayView,books:booksView,guides:guidesView,seo:seoView,money:moneyView,releases:releasesView,quality:qualityView,editor:editorView,settings:settingsView}[state.view]||todayView;$('#main').innerHTML=v();bindView();updateStaged()}
  function bindView(){
    $$('[data-open-site]').forEach(b=>b.onclick=()=>window.open(b.dataset.openSite,'_blank','noopener'));
    $$('[data-edit-file]').forEach(b=>b.onclick=()=>openEditor(b.dataset.editFile));
    $$('[data-unstage]').forEach(b=>b.onclick=()=>unstage(b.dataset.unstage));
    const bs=$('#bookSearch');if(bs)bs.oninput=()=>{$('#booksBody').innerHTML=booksRows((state.siteData?.books||[]).filter(b=>`${b.title} ${b.slug}`.toLowerCase().includes(bs.value.toLowerCase())))};
    const gf=$('#gscFile');if(gf)gf.onchange=e=>importGsc(e.target.files?.[0]);
    const ff=$('#fileFilter');if(ff)ff.oninput=()=>$$('.file-list [data-file]').forEach(b=>b.hidden=!b.dataset.file.toLowerCase().includes(ff.value.toLowerCase()));
    $$('.file-list [data-file]').forEach(b=>b.onclick=()=>loadEditorFile(b.dataset.file));
    const ss=$('#settingsSession');if(ss)ss.onclick=()=>state.user?disconnect():$('#sessionDialog').showModal();
  }
  async function openEditor(path){setView('editor');await loadEditorFile(path)}
  async function loadEditorFile(path){const pane=$('#editorPane');if(!pane)return;state.selectedFile=path;$$('.file-list [data-file]').forEach(b=>b.classList.toggle('active',b.dataset.file===path));pane.innerHTML='<div class="loading">Carregando arquivo…</div>';try{const f=await ghFile(path);const staged=state.staged.get(path);const content=staged?staged.content:f.text;pane.innerHTML=`<div class="file-meta"><span class="mono">${esc(path)}</span><span>${fmt(f.size)} bytes ${criticalFile(path)?'· arquivo sensível':''}</span></div><textarea id="fileEditor" class="json-editor" spellcheck="false"></textarea><div class="dialog-actions"><button id="reloadFile" class="btn secondary">Recarregar</button><button id="stageFile" class="btn">Adicionar ao change set</button></div><div id="fileError" class="form-error"></div>`;$('#fileEditor').value=content;$('#reloadFile').onclick=()=>loadEditorFile(path);$('#stageFile').onclick=()=>validateAndStage(path,$('#fileEditor').value)}catch(e){pane.innerHTML=`<div class="empty">Falha ao carregar: ${esc(e.message)}</div>`}}
  function validateAndStage(path,content){const err=$('#fileError');try{if(/\.json$|\.webmanifest$/.test(path))JSON.parse(content);if(path==='release.json')throw new Error('release.json é gerenciado automaticamente pelo publicador do painel. Edite o artefato de origem, não o hash authority.');if(path.startsWith('.github/'))throw new Error('Arquivos .github são bloqueados no editor.');if(content.length<2)throw new Error('Arquivo vazio não é permitido.');stage(path,content,path);if(err)err.textContent=''}catch(e){if(err)err.textContent=e.message}}
  async function importGsc(file){if(!file)return;try{const text=await file.text();const rows=parseCsv(text);if(!rows.length)throw new Error('CSV sem linhas utilizáveis');state.gsc={name:file.name,loadedAt:new Date().toISOString(),rows};sessionStorage.setItem('freedom-gsc-v1',JSON.stringify(state.gsc));toast(`${rows.length} linhas GSC importadas`);render()}catch(e){toast(e.message,'bad')}}
  function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delimiter=((lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length)?';':',';const split=line=>{const out=[];let s='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===delimiter&&!q){out.push(s);s=''}else s+=c}out.push(s);return out};const h=split(lines[0]).map(x=>x.trim().toLowerCase());const idx=(...names)=>h.findIndex(x=>names.includes(x));const qi=idx('query','consulta','queries'),pi=idx('page','página','pagina'),ci=idx('clicks','cliques'),ii=idx('impressions','impressões','impressoes'),ctri=idx('ctr'),poi=idx('position','posição','posicao');const num=v=>{const s=String(v??'').trim().replace('%','').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');return Number(s)||0};return lines.slice(1).map(l=>split(l)).map(c=>({query:qi>=0?c[qi]:'',page:pi>=0?c[pi]:'',key:(qi>=0?c[qi]:c[pi])||'',clicks:num(c[ci]),impressions:num(c[ii]),ctr:num(c[ctri]),position:num(c[poi])})).filter(r=>r.key||r.impressions||r.clicks)}
  async function connect(){const token=$('#tokenInput').value.trim(),err=$('#sessionError');err.textContent='';if(!token)return err.textContent='Informe o token.';$('#connectBtn').disabled=true;try{state.token=token;const u=await request('https://api.github.com/user');if(String(u.login).toLowerCase()!==OWNER.toLowerCase())throw new Error(`Token autenticou como ${u.login}; esperado ${OWNER}.`);const repo=await request(API);if(repo.permissions&&repo.permissions.push===false)throw new Error('O token não possui permissão de escrita neste repositório.');state.user=u;$('#tokenInput').value='';$('#sessionDialog').close();$('#sessionBtn').textContent=u.login;toast('Sessão GitHub validada');updateStaged();render()}catch(e){state.token=null;state.user=null;err.textContent=e.message}finally{$('#connectBtn').disabled=false}}
  function disconnect(){state.token=null;state.user=null;$('#sessionBtn').textContent='Modo leitura';updateStaged();toast('Token removido da memória');render()}
  async function preparePublish(){if(!state.token||!state.staged.size)return;$('#publishSummary').innerHTML=`<div class="action-list">${[...state.staged.values()].map(x=>`<div class="action-item"><div class="rank">✓</div><div><strong>${esc(x.label)}</strong><small class="mono">${esc(x.path)}</small></div></div>`).join('')}</div>`;$('#publishError').textContent='';$('#publishDialog').showModal()}
  async function publish(){const err=$('#publishError'),btn=$('#createPrBtn');err.textContent='';btn.disabled=true;btn.textContent='Criando PR…';try{
    if(!state.token)throw new Error('Sessão GitHub necessária.');
    const title=$('#prTitle').value.trim();if(title.length<8)throw new Error('Título do PR muito curto.');
    const base=await request(`${API}/git/ref/heads/main`),baseSha=base.object.sha,commit=await request(`${API}/git/commits/${baseSha}`),baseTree=commit.tree.sha;
    const relFile=await ghFile('release.json','main'),rel=JSON.parse(relFile.text),art=rel.artifacts||{};const tree=[];
    for(const x of state.staged.values()){if(x.path==='release.json')continue;const blob=await request(`${API}/git/blobs`,{method:'POST',body:JSON.stringify({content:x.content,encoding:'utf-8'}),headers:{'Content-Type':'application/json'}});tree.push({path:x.path,mode:'100644',type:'blob',sha:blob.sha});if(Object.prototype.hasOwnProperty.call(art,x.path))art[x.path]=await sha256(x.content)}
    const relText=JSON.stringify(rel,null,2)+'\n';const relChanged=relText!==relFile.text;if(relChanged){const rb=await request(`${API}/git/blobs`,{method:'POST',body:JSON.stringify({content:relText,encoding:'utf-8'}),headers:{'Content-Type':'application/json'}});tree.push({path:'release.json',mode:'100644',type:'blob',sha:rb.sha})}
    if(!tree.length)throw new Error('Nenhuma alteração efetiva.');
    const newTree=await request(`${API}/git/trees`,{method:'POST',body:JSON.stringify({base_tree:baseTree,tree}),headers:{'Content-Type':'application/json'}});
    const summary=$('#prSummary').value.trim()||'Alteração criada pelo Freedom Control Center.';
    const newCommit=await request(`${API}/git/commits`,{method:'POST',body:JSON.stringify({message:title,tree:newTree.sha,parents:[baseSha]}),headers:{'Content-Type':'application/json'}});
    const branch=`admin/${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,12)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0,5)}`;
    await request(`${API}/git/refs`,{method:'POST',body:JSON.stringify({ref:`refs/heads/${branch}`,sha:newCommit.sha}),headers:{'Content-Type':'application/json'}});
    const body=`## Freedom Control Center\n\n${summary}\n\n### Arquivos\n${[...state.staged.keys()].map(p=>`- \`${p}\``).join('\n')}\n${relChanged?'- `release.json` — hashes atualizados automaticamente\n':''}\n### Contrato\n- alteração criada em branch isolada;\n- main não foi escrita diretamente;\n- CI deve passar antes do merge;\n- arquivos de workflow são bloqueados pelo painel.\n`;
    const pr=await request(`${API}/pulls`,{method:'POST',body:JSON.stringify({title,head:branch,base:'main',body}),headers:{'Content-Type':'application/json'}});
    state.staged.clear();updateStaged();$('#publishDialog').close();toast(`PR #${pr.number} criado com sucesso`);window.open(pr.html_url,'_blank','noopener');await loadAll();
  }catch(e){err.textContent=e.message;toast(`Falha ao criar PR: ${e.message}`,'bad')}finally{btn.disabled=false;btn.textContent='Criar PR'}}
  async function init(){
    $('#app').hidden=false;$('#boot').remove();$$('#nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#refreshBtn').onclick=async()=>{await loadAll();toast('Dados atualizados')};$('#sessionBtn').onclick=()=>state.user?disconnect():$('#sessionDialog').showModal();$('#connectBtn').onclick=connect;$('#publishBtn').onclick=preparePublish;$('#publishClose').onclick=()=>$('#publishDialog').close();$('#createPrBtn').onclick=publish;$('#discardAll').onclick=()=>{state.staged.clear();updateStaged();$('#publishDialog').close();render();toast('Change set descartado')};await loadAll();
  }
  init().catch(e=>{console.error(e);document.body.innerHTML=`<div class="boot-screen"><div class="boot-mark">!</div><strong>Falha ao iniciar</strong><span>${esc(e.message)}</span></div>`});
})();
