(() => {
  'use strict';

  const OWNER='carloskk07', REPO='shopee', SITE='https://achadostube.com.br', GH='https://api.github.com', API=`${GH}/repos/${OWNER}/${REPO}`;
  const READ_HEADERS={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
  const SESSION_KEYS={changes:'freedom-change-set-v2',gscCurrent:'freedom-gsc-current-v2',gscBaseline:'freedom-gsc-baseline-v2'};
  const state={token:null,user:null,view:'command',repo:null,siteData:null,monetization:null,release:null,releaseText:null,prodRelease:null,adminRelease:null,cp:null,commits:[],pulls:[],runs:[],tree:[],sitemap:'',staged:new Map(),binaryStaged:new Map(),gsc:{current:null,baseline:null},selectedFile:null,selectedBase:null,cmdIndex:0};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(Number(n||0));
  const dec=(n,d=1)=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
  const pct=n=>`${dec(n,2)}%`;
  const short=s=>String(s||'').slice(0,8);
  const when=v=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
  const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const clone=v=>JSON.parse(JSON.stringify(v));
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const toB64=s=>{const b=new TextEncoder().encode(s);let x='';for(let i=0;i<b.length;i+=0x8000)x+=String.fromCharCode(...b.subarray(i,i+0x8000));return btoa(x)};
  const decode64=s=>new TextDecoder().decode(Uint8Array.from(atob(String(s).replace(/\n/g,'')),c=>c.charCodeAt(0)));
  const encodePath=p=>p.split('/').map(encodeURIComponent).join('/');
  const reEsc=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');

  function toast(msg,kind='good'){const t=$('#toast');t.textContent=msg;t.className=`toast show ${kind}`;clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',3600)}
  function ghHeaders(){return {...READ_HEADERS,...(state.token?{'Authorization':`Bearer ${state.token}`}:{})}}
  async function request(url,opts={}){const r=await fetch(url,{...opts,headers:{...ghHeaders(),...(opts.headers||{})}});if(!r.ok){let msg=`${r.status} ${r.statusText}`;try{const j=await r.json();msg=j.message||msg}catch(_){}throw new Error(msg)}return r.status===204?null:r.json()}
  async function fetchText(url,opts={}){const r=await fetch(url,{...opts,headers:{...ghHeaders(),...(opts.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
  async function ghFile(path,ref='main'){const j=await request(`${API}/contents/${encodePath(path)}?ref=${encodeURIComponent(ref)}`);if(j.type!=='file')throw new Error(`${path} não é arquivo`);return {path:j.path,size:j.size,sha:j.sha,text:decode64(j.content)}}
  async function sha256(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function b64Bytes(s){return Uint8Array.from(atob(String(s||'').replace(/\s/g,'')),c=>c.charCodeAt(0))}
  async function sha256Base64(s){const b=await crypto.subtle.digest('SHA-256',b64Bytes(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function allStaged(){return [...state.staged.values(),...state.binaryStaged.values()]}
  function stagedCount(){return state.staged.size+state.binaryStaged.size}
  function binaryPathAllowed(path){return /^assets\/covers\/capa-[a-z0-9-]+\.webp$/.test(path)||/^ebook\/[a-z0-9-]+\.pdf$/.test(path)}
  function stableEqual(a,b){return !!a&&!!b&&JSON.stringify(a)===JSON.stringify(b)}
  function pill(text,kind=''){return `<span class="pill ${kind}">${esc(text)}</span>`}
  function metric(label,value,detail='',kind=''){return `<section class="card metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small class="${kind}">${esc(detail)}</small></section>`}
  function card(title,body,subtitle='',right=''){return `<section class="card pad"><div class="card-head"><div><span class="kicker">${esc(subtitle||'Control plane')}</span><h3>${esc(title)}</h3></div>${right}</div>${body}</section>`}
  function intro(title,text,badges=''){return `<section class="card pad"><div class="card-head"><div><span class="kicker">Freedom operational system</span><h2>${esc(title)}</h2><p>${esc(text)}</p></div>${badges}</div></section>`}
  function openUrl(url){window.open(url,'_blank','noopener,noreferrer')}
  function currentBranch(){return state.commits[0]?.sha||''}

  function persistStaged(){try{sessionStorage.setItem(SESSION_KEYS.changes,JSON.stringify([...state.staged.values()].filter(x=>!x.volatile)))}catch(_){}updateStagedUi()}
  function restoreSession(){
    try{const s=sessionStorage.getItem(SESSION_KEYS.changes);if(s){for(const x of JSON.parse(s))if(x?.path&&typeof x.content==='string')state.staged.set(x.path,x)}}catch(_){}
    for(const k of ['current','baseline']){try{const s=sessionStorage.getItem(k==='current'?SESSION_KEYS.gscCurrent:SESSION_KEYS.gscBaseline);if(s)state.gsc[k]=JSON.parse(s)}catch(_){}}
  }
  function updateStagedUi(){const n=stagedCount();for(const id of ['#stagedBadge','#navStaged']){const el=$(id);if(el)el.textContent=n}const p=$('#publishBtn');if(p)p.disabled=!state.token||!n}
  function stage(path,content,label=path,baseContent=''){
    if(!isEditable(path))return toast(`Edição bloqueada pela política: ${path}`,'bad');
    if(path==='release.json')return toast('release.json é gerenciado automaticamente pelo publicador','warn');
    const base=state.staged.get(path)?.baseContent ?? baseContent;
    state.staged.set(path,{path,content,label,baseContent:base,updatedAt:new Date().toISOString()});persistStaged();toast(`${label} entrou no Change Set`);render();
  }
  function unstage(path){state.staged.delete(path);state.binaryStaged.delete(path);persistStaged();render()}
  function clearStaged(){state.staged.clear();state.binaryStaged.clear();persistStaged();render()}
  function config(){return state.cp||{security:{blockedPrefixes:['.github/','admin/','.git/'],blockedFiles:['release.json'],editableExtensions:['.html','.json','.xml','.txt','.css','.md'],criticalPaths:[]},publishing:{maxFilesPerChangeSet:12,branchPrefix:'control-center/'},seo:{ctrOpportunity:{minImpressions:30,maxPosition:10,maxCtrPct:2},strikingDistance:{minImpressions:20,minPosition:8,maxPosition:20},cannibalization:{minTotalImpressions:20,secondPageShare:.2}},experiments:[]}}
  function isEditable(path){const c=config().security||{};if((c.blockedPrefixes||[]).some(p=>path.startsWith(p)))return false;if((c.blockedFiles||[]).includes(path))return false;return (c.editableExtensions||[]).some(e=>path.endsWith(e))}
  function isCritical(path){return (config().security?.criticalPaths||[]).includes(path)}
  function fileRisk(path){if(isCritical(path))return 'high';if(/\.(xml|css)$/.test(path)||path.includes('/'))return 'medium';return 'low'}

  async function loadAll(){
    $('#envLabel').textContent='Sincronizando…';$('#envDot').className='';
    const safe=async(fn,fallback)=>{try{return await fn()}catch(e){console.warn(e);return fallback}};
    const [repo,sd,mon,relFile,prod,adminRel,cp,commits,pulls,runs,tree,sitemap]=await Promise.all([
      safe(()=>request(API),state.repo),
      safe(()=>ghFile('site-data.generated.json').then(x=>JSON.parse(x.text)),state.siteData),
      safe(()=>ghFile('monetization.json').then(x=>JSON.parse(x.text)),state.monetization),
      safe(()=>ghFile('release.json'),null),
      safe(()=>fetch(`${SITE}/release.json?fcc=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),state.prodRelease),
      safe(()=>fetch(`${SITE}/admin/release.json?fcc=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),state.adminRelease),
      safe(()=>ghFile('admin/control-plane.json').then(x=>JSON.parse(x.text)),state.cp),
      safe(()=>request(`${API}/commits?per_page=16`),state.commits||[]),
      safe(()=>request(`${API}/pulls?state=open&per_page=20`),state.pulls||[]),
      safe(()=>request(`${API}/actions/runs?per_page=30`).then(x=>x.workflow_runs||[]),state.runs||[]),
      safe(()=>request(`${API}/git/trees/main?recursive=1`).then(x=>x.tree||[]),state.tree||[]),
      safe(()=>ghFile('sitemap.xml').then(x=>x.text),state.sitemap||'')
    ]);
    if(relFile){state.releaseText=relFile.text;state.release=JSON.parse(relFile.text)}
    Object.assign(state,{repo,siteData:sd,monetization:mon,prodRelease:prod,adminRelease:adminRel,cp,commits,pulls,runs,tree,sitemap});
    const exact=stableEqual(state.release,state.prodRelease);$('#envDot').className=exact?'good':'bad';$('#envLabel').textContent=exact?'Produção sincronizada':'Release divergente';$('#envDetail').textContent=exact?`main ${short(currentBranch())}`:'investigar antes de publicar';$('#cpVersion').textContent=state.cp?.version||'—';
    render();
  }

  function gscStats(dataset){const rows=dataset?.rows||[];const clicks=rows.reduce((a,r)=>a+r.clicks,0),imp=rows.reduce((a,r)=>a+r.impressions,0),ctr=imp?clicks/imp*100:0,pos=imp?rows.reduce((a,r)=>a+r.position*r.impressions,0)/imp:0;return {clicks,imp,ctr,pos}}
  function delta(curr,base,invert=false){if(base===null||base===undefined||!Number.isFinite(base))return {text:'sem baseline',kind:''};const d=curr-base;if(Math.abs(d)<.001)return {text:'sem mudança',kind:'trend-flat'};const good=invert?d<0:d>0;return {text:`${d>0?'+':''}${dec(d,1)}`,kind:good?'trend-up':'trend-down'}}
  function latestDatasetDate(ds){const dates=(ds?.rows||[]).map(r=>r.date).filter(Boolean).sort();return dates.at(-1)||ds?.endDate||null}
  function datasetLabel(ds){if(!ds)return 'não importado';const end=latestDatasetDate(ds);return end?`até ${end}`:(ds.fileName||'CSV importado')}

  function qualityModel(){
    const exact=stableEqual(state.release,state.prodRelease), runs=state.runs||[], recent=runs.slice(0,20), failed=recent.filter(r=>r.status==='completed'&&r.conclusion&&!['success','skipped'].includes(r.conclusion));
    const books=state.siteData?.books||[], guides=state.siteData?.guides||[], slugs=books.map(b=>b.slug).filter(Boolean), dup=slugs.filter((x,i)=>slugs.indexOf(x)!==i);
    const artifacts=Object.keys(state.release?.artifacts||{}), support=state.monetization?.support, aff=state.monetization?.affiliates, premium=state.monetization?.premium;
    const guideOk=guides.length>=6, catalogOk=books.length>0&&!dup.length&&books.filter(b=>b.available).every(b=>b.slug&&b.title), moneyOk=!!support?.url&&(aff?.enabled!==true||((aff?.offers||[]).length>0));
    const adminOk=state.adminRelease?.schema==='freedom-admin-release-v1';
    const gates=[
      {name:'RELEASE_PARITY',ok:exact,weight:25,detail:exact?'repositório = produção':'release.json diverge da produção'},
      {name:'CI_RECENT',ok:failed.length===0,weight:20,detail:failed.length?`${failed.length} workflow(s) recente(s) fora de success`:'pipelines recentes sem falha'},
      {name:'CATALOG_TRUTH',ok:catalogOk,weight:15,detail:`${books.length} livros · ${dup.length} slugs duplicados`},
      {name:'TOPICAL_GUIDES',ok:guideOk,weight:10,detail:`${guides.length} guias editoriais`},
      {name:'MONETIZATION_GUARD',ok:!!moneyOk,weight:10,detail:aff?.enabled?'afiliados ativos com ofertas':'afiliados inativos ou controlados'},
      {name:'ADMIN_RELEASE',ok:adminOk,weight:10,detail:adminOk?'admin release reconhecido':'admin release não confirmado'},
      {name:'SEARCH_EVIDENCE',ok:!!state.gsc.current,weight:10,detail:state.gsc.current?datasetLabel(state.gsc.current):'sem dataset GSC atual'}
    ];
    const score=Math.round(gates.reduce((a,g)=>a+(g.ok?g.weight:0),0));return {score,gates,failed,exact,artifacts,books,guides};
  }

  function seoRows(){return state.gsc.current?.rows||[]}
  function rowKey(r){return [normalize(r.query),r.page||'',r.device||''].join('|')}
  function baselineMap(){return new Map((state.gsc.baseline?.rows||[]).map(r=>[rowKey(r),r]))}
  function opportunityEngine(){
    const c=config().seo||{}, ctrT=c.ctrOpportunity||{}, sd=c.strikingDistance||{}, base=baselineMap();
    return seoRows().map(r=>{
      const b=base.get(rowKey(r));let type='OBSERVE',score=0,why=[];
      const imp=r.impressions,pos=r.position,ctr=r.ctr,clicks=r.clicks;
      score+=Math.min(35,Math.log10(imp+1)*16);if(pos<=10)score+=20;else if(pos<=20)score+=17;else if(pos<=40)score+=7;
      if(imp>=(ctrT.minImpressions||30)&&pos<=(ctrT.maxPosition||10)&&ctr<(ctrT.maxCtrPct||2)){type='CTR_OPPORTUNITY';score+=28;why.push('top 10 com CTR abaixo do gate')}
      else if(imp>=(sd.minImpressions||20)&&pos>=(sd.minPosition||8)&&pos<=(sd.maxPosition||20)){type='STRIKING_DISTANCE';score+=24;why.push('posição próxima da primeira página')}
      else if(imp>=30&&clicks===0&&pos<=20){type='ZERO_CLICK_SIGNAL';score+=20;why.push('impressões sem clique em posição acionável')}
      if(b){const impGrowth=b.impressions?imp/b.impressions:0;const posGain=b.position-pos;if(imp>=20&&impGrowth>=1.5){type=type==='OBSERVE'?'BREAKOUT':type;score+=12;why.push('impressões acelerando')};if(posGain>=2){score+=10;why.push('posição melhorou')};if(posGain<=-2){score+=4;why.push('posição piorou; revisar antes de perder sinal')}}
      if(r.page?.endsWith('.pdf'))why.push('resultado PDF');
      return {...r,baseline:b||null,type,score:Math.min(100,Math.round(score)),why:why.join(' · ')||'evidência insuficiente para ação'};
    }).sort((a,b)=>b.score-a.score||b.impressions-a.impressions)
  }
  function cannibalization(){
    const t=config().seo?.cannibalization||{}, groups=new Map();for(const r of seoRows()){if(!r.query||!r.page)continue;const q=normalize(r.query);if(!groups.has(q))groups.set(q,[]);groups.get(q).push(r)}
    const out=[];for(const [q,rs] of groups){const by=new Map();for(const r of rs)by.set(r.page,(by.get(r.page)||0)+r.impressions);const pages=[...by].sort((a,b)=>b[1]-a[1]),total=pages.reduce((a,x)=>a+x[1],0);if(pages.length>=2&&total>=(t.minTotalImpressions||20)&&(pages[1][1]/total)>=(t.secondPageShare||.2))out.push({query:q,total,pages})}return out.sort((a,b)=>b.total-a.total)
  }
  function pdfHtmlConflicts(){
    const groups=new Map();for(const r of seoRows()){if(!r.query||!r.page)continue;const q=normalize(r.query);if(!groups.has(q))groups.set(q,[]);groups.get(q).push(r)}
    const out=[];for(const [q,rs] of groups){const pdf=rs.filter(r=>/\.pdf(?:$|\?)/i.test(r.page)),html=rs.filter(r=>!/\.pdf(?:$|\?)/i.test(r.page));if(pdf.length&&html.length)out.push({query:q,pdf,html,impressions:rs.reduce((a,r)=>a+r.impressions,0)})}return out.sort((a,b)=>b.impressions-a.impressions)
  }
  function experimentModel(exp){
    const match=r=>{const q=normalize(r.query);return (exp.queryContains||[]).some(x=>q.includes(normalize(x)))||[exp.targetHtml,exp.targetPdf].includes(r.page)};
    const cur=(state.gsc.current?.rows||[]).filter(match),base=(state.gsc.baseline?.rows||[]).filter(match),cs=gscStats({rows:cur}),bs=gscStats({rows:base});
    const today=new Date(),min=new Date(`${exp.minimumDecisionDate}T12:00:00`),dateReady=today>=min;const dataEnd=latestDatasetDate(state.gsc.current);const evidenceReady=!!dataEnd&&dataEnd>=exp.startedAt;
    let status='WAITING_DATA';if(dateReady&&evidenceReady&&cs.imp>=10)status='DECISION_WINDOW';else if(evidenceReady)status='OBSERVING';
    const html=gscStats({rows:cur.filter(r=>r.page===exp.targetHtml)}),pdf=gscStats({rows:cur.filter(r=>r.page===exp.targetPdf)});
    return {exp,cur,base,cs,bs,html,pdf,status,dateReady,evidenceReady,dataEnd};
  }

  function queueModel(){
    const q=qualityModel(), items=[];
    if(!q.exact)items.push({p:'P0',title:'Release divergente',detail:'Bloqueie novas publicações até main e produção convergirem.',score:100,view:'deploy'});
    if(q.failed.length)items.push({p:'P0',title:'CI recente exige diagnóstico',detail:`${q.failed.length} execução(ões) fora de success entre as recentes.`,score:96,view:'deploy'});
    const opp=opportunityEngine().filter(x=>x.type!=='OBSERVE')[0];if(opp)items.push({p:'P1',title:`${opp.type}: ${opp.query||opp.page}`,detail:`${fmt(opp.impressions)} imp · posição ${dec(opp.position,1)} · CTR ${pct(opp.ctr)}. ${opp.why}`,score:opp.score,view:'seo'});
    const exp=(config().experiments||[]).map(experimentModel)[0];if(exp&&exp.status==='DECISION_WINDOW')items.push({p:'P1',title:`Experimento pronto para decisão: ${exp.exp.name}`,detail:`Janela mínima atingida e GSC atual já cobre ${exp.dataEnd}.`,score:90,view:'experiments'});
    if(!state.gsc.current)items.push({p:'P1',title:'Carregar Search Console atual',detail:'Sem dados recentes o control plane não deve inventar prioridades orgânicas.',score:85,view:'seo'});
    if(state.gsc.current&&!state.gsc.baseline)items.push({p:'P2',title:'Adicionar baseline GSC',detail:'A comparação temporal separa crescimento real de fotografia isolada.',score:70,view:'seo'});
    if(!items.length)items.push({p:'OK',title:'Nenhum bloqueio operacional',detail:'Preserve estabilidade e trabalhe só na oportunidade com maior evidência.',score:100,view:'quality'});
    return items.sort((a,b)=>b.score-a.score).slice(0,6)
  }

  function commandView(){
    const q=qualityModel(),cs=gscStats(state.gsc.current),bs=gscStats(state.gsc.baseline),dImp=state.gsc.baseline?delta(cs.imp,bs.imp):{text:'sem baseline',kind:''},dPos=state.gsc.baseline?delta(cs.pos,bs.pos,true):{text:'sem baseline',kind:''},items=queueModel(), latest=state.runs[0],exp=(config().experiments||[])[0];
    return `<div class="stack"><div class="grid-2"><section class="card hero"><div><span class="kicker">Command center · evidence first</span><h2>${q.score>=90?'Operação saudável. Preserve estabilidade e ataque somente o próximo sinal de alto retorno.':q.score>=70?'Operação funcional, com riscos específicos que devem ser resolvidos por prioridade.':'Há gates críticos abertos antes da próxima publicação.'}</h2><p>O V2 combina verdade de produção, GitHub, catálogo, monetização, Search Console, experimentos e Change Sets em uma fila única de decisão.</p></div><div class="status-row">${pill(`Quality ${q.score}/100`,q.score>=90?'good':q.score>=70?'warn':'bad')}${pill(`main ${short(currentBranch())}`,q.exact?'good':'bad')}${pill(`${state.pulls.length} PR aberto${state.pulls.length===1?'':'s'}`,state.pulls.length?'warn':'good')}${pill(state.token?`escrita: ${state.user?.login||'autorizada'}`:'somente leitura',state.token?'blue':'')}</div></section>${card('Fila de decisão',`<div class="queue">${items.map(x=>`<button class="queue-item" data-go="${esc(x.view)}"><div class="queue-rank">${esc(x.p)}</div><div><strong>${esc(x.title)}</strong><span>${esc(x.detail)}</span></div><div class="queue-score">${fmt(x.score)}</div></button>`).join('')}</div>`,'prioridade por risco + ROI')}</div>
      <div class="metric-grid">${metric('Quality score',`${q.score}/100`,q.gates.filter(g=>g.ok).length+' de '+q.gates.length+' gates')}${metric('Impressões GSC',state.gsc.current?fmt(cs.imp):'—',dImp.text,dImp.kind)}${metric('Posição média',state.gsc.current?dec(cs.pos,1):'—',dPos.text,dPos.kind)}${metric('Último pipeline',latest?.conclusion||latest?.status||'—',latest?.name||'sem histórico',latest?.conclusion==='success'?'good':latest?.conclusion?'bad':'')}</div>
      <div class="grid-2">${experimentMini(exp)}${pipelineTimeline()}</div></div>`
  }
  function experimentMini(exp){if(!exp)return card('Experimento ativo','<div class="empty"><strong>Nenhum experimento registrado</strong><p>O control plane não criará um automaticamente.</p></div>','causal attribution');const x=experimentModel(exp);return card('Experimento ativo',`<div class="experiment"><div><div class="chips">${pill(x.status,x.status==='DECISION_WINDOW'?'good':x.status==='OBSERVING'?'blue':'warn')}${pill(`início ${exp.startedAt}`)}</div><h3>${esc(exp.name)}</h3><p>${esc(exp.decisionRule)}</p></div><div class="experiment-side"><strong>${x.cs.impressions?fmt(x.cs.impressions):fmt(x.cs.imp)}</strong><span>impressões do cluster no atual</span><div style="margin-top:8px">${pill(x.dataEnd?`GSC até ${x.dataEnd}`:'sem data final',x.evidenceReady?'good':'warn')}</div></div></div>`,'observação controlada',`<button class="mini-btn" data-go="experiments">Abrir</button>`)}
  function pipelineTimeline(){const rows=(state.runs||[]).slice(0,7).map(r=>`<div class="timeline-item ${r.conclusion==='success'?'good':r.conclusion?'bad':''}"><strong>${esc(r.name)} · ${esc(r.conclusion||r.status)}</strong><span>${esc(r.display_title||'')} · ${short(r.head_sha)} · ${when(r.updated_at||r.created_at)}</span></div>`).join('');return card('Atividade operacional',`<div class="timeline">${rows||'<div class="empty">Sem execuções recentes</div>'}</div>`,'GitHub Actions')}

  function contentView(){
    const books=state.siteData?.books||[],guides=state.siteData?.guides||[],missingPdf=books.filter(b=>b.available&&!b.pdfUrl),missingCover=books.filter(b=>b.available&&!b.cover),slugs=books.map(b=>b.slug).filter(Boolean),dups=[...new Set(slugs.filter((s,i)=>slugs.indexOf(s)!==i))];
    const rows=books.map(b=>`<tr data-content-row data-search="${esc(normalize(`${b.title} ${b.slug} ${(b.tags||b.themes||[]).join(' ')}`))}"><td><div class="title-cell"><img class="cover" src="${esc(b.cover||'/assets/covers/logo-freedom-book-redonda.webp')}" alt=""><div><strong>${esc(b.title)}</strong><small>${esc(b.slug||'sem slug')}</small></div></div></td><td>${pill(b.available?'Publicado':'Planejado',b.available?'good':'warn')}</td><td>${esc((b.tags||b.themes||[]).slice(0,4).join(' · ')||'—')}</td><td>${b.pdfUrl?pill('PDF','good'):pill('Sem PDF',b.available?'bad':'')}</td><td><div class="small-actions"><button class="mini-btn" data-open="${esc(b.pageUrl||`${SITE}/${b.slug}`)}">Ver</button>${b.slug?`<button class="mini-btn" data-edit="${esc(b.slug)}.html">Landing</button>`:''}${b.pdfUrl?`<button class="mini-btn" data-open="${esc(b.pdfUrl)}">PDF</button>`:''}</div></td></tr>`).join('');
    const grows=guides.map(g=>`<tr data-guide-row data-search="${esc(normalize(`${g.title} ${g.slug} ${(g.tags||g.themes||[]).join(' ')}`))}"><td><strong>${esc(g.title)}</strong><br><small>${esc(g.description||'')}</small></td><td class="mono">/guias/${esc(g.slug||'')}</td><td>${esc((g.tags||g.themes||[]).slice(0,3).join(' · ')||'Editorial')}</td><td><div class="small-actions"><button class="mini-btn" data-open="${esc(g.url||`${SITE}/guias/${g.slug}`)}">Ver</button><button class="mini-btn" data-edit="guias/${esc(g.slug)}.html">Editar</button></div></td></tr>`).join('');
    return `<div class="stack">${intro('Conteúdo & catálogo','Visão operacional do inventário publicado. Mudanças de conteúdo passam pelo editor seguro e PR; dados gerados continuam sujeitos ao CI do site.',`${pill(`${books.length} livros`)} ${pill(`${guides.length} guias`)}`)}<div class="metric-grid">${metric('Livros publicados',fmt(books.filter(b=>b.available).length),`${books.length} registros`)}${metric('PDF ausente',fmt(missingPdf.length),missingPdf.length?'exige correção':'nenhum',missingPdf.length?'bad':'good')}${metric('Capas ausentes',fmt(missingCover.length),missingCover.length?'revisar catálogo':'nenhuma',missingCover.length?'warn':'good')}${metric('Slugs duplicados',fmt(dups.length),dups.join(', ')||'nenhum',dups.length?'bad':'good')}</div>
      ${card('Livros',`<div class="toolbar"><input id="contentSearch" class="search" placeholder="Buscar livro, slug ou tema…"><div class="toolbar-right"><button class="btn primary" data-new-book>+ Novo livro</button>${pill('fonte: site-data.generated.json')}</div></div><div class="table-wrap"><table><thead><tr><th>Livro</th><th>Status</th><th>Temas</th><th>Arquivo</th><th>Ações</th></tr></thead><tbody>${rows||'<tr><td colspan="5">Sem catálogo</td></tr>'}</tbody></table></div>`,'inventário editorial')}
      ${card('Guias de autoridade',`<div class="table-wrap"><table><thead><tr><th>Guia</th><th>Rota</th><th>Temas</th><th>Ações</th></tr></thead><tbody>${grows||'<tr><td colspan="4">Sem guias</td></tr>'}</tbody></table></div>`,'topical authority')}</div>`
  }

  function seoView(){
    const cur=gscStats(state.gsc.current),base=gscStats(state.gsc.baseline),opps=opportunityEngine(),actionable=opps.filter(x=>x.type!=='OBSERVE'),cann=cannibalization(),conf=pdfHtmlConflicts();
    const dClicks=state.gsc.baseline?delta(cur.clicks,base.clicks):{text:'sem baseline',kind:''},dImp=state.gsc.baseline?delta(cur.imp,base.imp):{text:'sem baseline',kind:''},dCtr=state.gsc.baseline?delta(cur.ctr,base.ctr):{text:'sem baseline',kind:''},dPos=state.gsc.baseline?delta(cur.pos,base.pos,true):{text:'sem baseline',kind:''};
    const list=actionable.slice(0,18).map(r=>`<div class="seo-opportunity"><div class="score">${r.score}</div><div><strong>${esc(r.query||r.page||r.key||'Dimensão')}</strong><span>${esc(r.type)} · ${esc(r.why)}</span></div><div class="num"><b>${fmt(r.impressions)}</b><small>impressões</small></div><div class="num"><b>${pct(r.ctr)}</b><small>CTR</small></div><div class="num"><b>${dec(r.position,1)}</b><small>posição</small></div><div class="num"><b>${fmt(r.clicks)}</b><small>cliques</small></div></div>`).join('');
    return `<div class="stack">${intro('SEO Intelligence','Dois períodos podem ser comparados localmente. O motor prioriza oportunidades com evidência, mostra tendências e separa conflito de páginas de criação prematura de novas URLs.',`${pill(state.gsc.current?`Atual: ${datasetLabel(state.gsc.current)}`:'Atual ausente',state.gsc.current?'good':'warn')} ${pill(state.gsc.baseline?`Baseline: ${datasetLabel(state.gsc.baseline)}`:'Baseline ausente',state.gsc.baseline?'blue':'')}`)}
      <div class="metric-grid">${metric('Cliques',state.gsc.current?fmt(cur.clicks):'—',dClicks.text,dClicks.kind)}${metric('Impressões',state.gsc.current?fmt(cur.imp):'—',dImp.text,dImp.kind)}${metric('CTR',state.gsc.current?pct(cur.ctr):'—',dCtr.text,dCtr.kind)}${metric('Posição',state.gsc.current?dec(cur.pos,1):'—',dPos.text,dPos.kind)}</div>
      <section class="card pad"><div class="toolbar"><div class="toolbar-left"><label class="btn ghost">Importar atual<input data-gsc="current" type="file" accept=".csv,text/csv" hidden></label><label class="btn ghost">Importar baseline<input data-gsc="baseline" type="file" accept=".csv,text/csv" hidden></label>${state.gsc.current?`<input class="search" style="min-width:160px" type="date" data-gsc-end="current" value="${esc(state.gsc.current.endDate||latestDatasetDate(state.gsc.current)||'')}">`:''}</div><div class="toolbar-right"><button class="mini-btn" data-clear-gsc>Limpar GSC</button>${pill(`${actionable.length} oportunidades`,actionable.length?'warn':'good')}</div></div><div class="callout"><strong>Privacidade</strong><span>Os CSVs ficam somente em sessionStorage desta aba/sessão do navegador. Nenhum dado do Search Console é enviado ao GitHub ou a terceiros.</span></div></section>
      <div class="grid-2">${card('Oportunidades ordenadas por ROI',list?`<div style="border:1px solid #202834;border-radius:13px;overflow:hidden">${list}</div>`:'<div class="empty"><strong>Nenhuma oportunidade acionável</strong><p>Importe GSC atual ou preserve observação até existir evidência suficiente.</p></div>','thresholds + tendência')}${card('Conflitos de autoridade',`${conf.length?`<div class="callout warn"><strong>PDF × HTML</strong><span>${conf.length} consulta(s) mostram PDF e HTML concorrendo na mesma intenção. Isso merece diagnóstico antes de criar outra página.</span></div>`:'<div class="callout"><strong>PDF × HTML</strong><span>Nenhum conflito comprovado no dataset atual.</span></div>'}<div style="height:8px"></div>${cann.length?`<div class="callout warn"><strong>Canibalização</strong><span>${cann.length} consulta(s) ultrapassam o gate de distribuição entre duas ou mais páginas.</span></div>`:'<div class="callout"><strong>Canibalização</strong><span>Nenhum caso passou o gate configurado.</span></div>'}${conf.slice(0,4).map(x=>`<div class="gate"><div><strong>${esc(x.query)}</strong><span>${fmt(x.impressions)} impressões combinadas</span></div>${pill('revisar','warn')}</div>`).join('')}${cann.slice(0,4).map(x=>`<div class="gate"><div><strong>${esc(x.query)}</strong><span>${x.pages.length} páginas · ${fmt(x.total)} impressões</span></div>${pill('cannibalização','warn')}</div>`).join('')}`,'authority diagnostics')}</div></div>`
  }

  function experimentsView(){const exps=(config().experiments||[]).map(experimentModel);const body=exps.map(x=>{const cs=x.cs,bs=x.bs,d=state.gsc.baseline?delta(cs.imp,bs.imp):{text:'sem baseline',kind:''};return `<section class="card pad"><div class="card-head"><div><span class="kicker">${esc(x.exp.id)}</span><h2>${esc(x.exp.name)}</h2><p>${esc(x.exp.decisionRule)}</p></div>${pill(x.status,x.status==='DECISION_WINDOW'?'good':x.status==='OBSERVING'?'blue':'warn')}</div><div class="metric-grid">${metric('Impressões cluster',fmt(cs.imp),d.text,d.kind)}${metric('HTML',fmt(x.html.imp),'impressões')}${metric('PDF',fmt(x.pdf.imp),'impressões')}${metric('Fim GSC',x.dataEnd||'—',x.evidenceReady?'cobre início do experimento':'ainda sem evidência pós-início',x.evidenceReady?'good':'warn')}</div><div style="height:12px"></div><div class="grid-2"><div class="callout ${x.dateReady?'':'warn'}"><strong>Janela temporal</strong><span>Início: ${esc(x.exp.startedAt)} · decisão mínima: ${esc(x.exp.minimumDecisionDate)} · ${x.dateReady?'data mínima atingida':'não alterar antes da data mínima sem P0 real'}.</span></div><div class="callout ${x.evidenceReady?'':'warn'}"><strong>Janela de dados</strong><span>${x.evidenceReady?`O dataset atual alcança ${esc(x.dataEnd)}.`:'O dataset atual ainda não comprova cobertura posterior ao início do experimento.'}</span></div></div></section>`}).join('');return `<div class="stack">${intro('Experimentos & causalidade','Mudanças de SEO passam a ter início, janela mínima, alvo e regra de decisão explícitos. Isso reduz intervenções simultâneas e protege atribuição.',pill(`${exps.length} experimento${exps.length===1?'':'s'}`))}${body||'<section class="card pad"><div class="empty"><strong>Sem experimentos registrados</strong><p>Adicione ao control-plane somente quando houver hipótese e métrica reais.</p></div></section>'}</div>`}

  function moneyView(){const m=state.monetization||{},support=m.support||{},aff=m.affiliates||{},premium=m.premium||{};return `<div class="stack">${intro('Monetização','O V2 trata monetização como um control plane com guardrails, não como inserção oportunista de links. Alterações são revisadas no mesmo Change Set.',`${pill(support.enabled?'apoio ativo':'apoio inativo',support.enabled?'good':'warn')} ${pill(aff.enabled?'afiliados ativos':'afiliados inativos',aff.enabled?'warn':'good')}`)}<div class="metric-grid">${metric('Apoio',support.enabled?'Ativo':'Inativo',support.url||'sem URL',support.enabled?'good':'')}${metric('Ofertas afiliadas',fmt((aff.offers||[]).length),aff.enabled?'módulo habilitado':'módulo desligado')}${metric('Premium',premium.enabled?'Ativo':'Inativo',`${(premium.offers||[]).length} ofertas`)}${metric('Affiliate rel',m.guardrails?.affiliateRel||'—','proteção de link')}</div><div class="grid-3">${moneyCard('Apoio direto',support.enabled,'LivePix / suporte editorial','support')}${moneyCard('Afiliados',aff.enabled,`${(aff.offers||[]).length} ofertas configuradas`,'affiliates')}${moneyCard('Premium',premium.enabled,`${(premium.offers||[]).length} ofertas configuradas`,'premium')}</div>${card('Configuração avançada',`<div class="callout"><strong>Arquivo autoridade</strong><span>monetization.json continua sendo a fonte. Use o editor para URLs, ofertas e guardrails; o CI público permanece a última autoridade antes do merge.</span></div><div style="margin-top:10px"><button class="btn ghost" data-edit="monetization.json">Abrir monetization.json</button></div>`,'policy file')}</div>`}
  function moneyCard(title,enabled,detail,key){const canEnable=key==='support'||((state.monetization?.[key]?.offers||[]).length>0);return `<section class="card pad"><div class="card-head"><div><span class="kicker">${enabled?'enabled':'disabled'}</span><h3>${esc(title)}</h3><p>${esc(detail)}</p></div>${pill(enabled?'ON':'OFF',enabled?'good':'')}</div><button class="btn ghost" data-money-toggle="${esc(key)}" ${!enabled&&!canEnable?'disabled':''}>${enabled?'Desativar':'Ativar'}</button>${!enabled&&!canEnable?'<p style="font-size:9px;color:var(--muted)">Adicione uma oferta válida antes de habilitar.</p>':''}</section>`}
  async function toggleMoney(key){if(!state.monetization)return;const next=clone(state.monetization),section=next[key];if(!section)return;const enable=!section.enabled;if(enable&&key!=='support'&&!(section.offers||[]).length)return toast('Não é permitido ativar sem ofertas configuradas','warn');const base=state.staged.get('monetization.json')?.baseContent||JSON.stringify(state.monetization,null,2)+'\n';section.enabled=enable;stage('monetization.json',JSON.stringify(next,null,2)+'\n','Monetização',base);state.monetization=next}

  function deployView(){const q=qualityModel();const runRows=(state.runs||[]).slice(0,15).map(r=>`<tr><td><strong>${esc(r.name)}</strong><br><small>${esc(r.display_title||'')}</small></td><td>${pill(r.conclusion||r.status,r.conclusion==='success'?'good':r.conclusion?'bad':'warn')}</td><td class="mono">${short(r.head_sha)}</td><td>${when(r.updated_at||r.created_at)}</td><td><button class="mini-btn" data-open="${esc(r.html_url||'')}">Abrir</button></td></tr>`).join('');const prs=(state.pulls||[]).map(p=>`<tr><td><strong>#${p.number} ${esc(p.title)}</strong></td><td>${pill(p.draft?'draft':'open',p.draft?'warn':'blue')}</td><td class="mono">${short(p.head?.sha)}</td><td>${when(p.updated_at)}</td><td><button class="mini-btn" data-open="${esc(p.html_url)}">Abrir</button></td></tr>`).join('');return `<div class="stack">${intro('Deploy & Releases','GitHub Pages continua sendo produção. O admin observa paridade, pipelines, PRs e autoridade de release sem criar uma segunda fonte de verdade.',pill(q.exact?'EXACT':'DIVERGENT',q.exact?'good':'bad'))}<div class="metric-grid">${metric('Main',short(currentBranch())||'—','commit aprovado')}${metric('Artefatos release',fmt(q.artifacts.length),'contrato editorial')}${metric('PRs abertos',fmt(state.pulls.length),'fila de revisão')}${metric('CI com falha',fmt(q.failed.length),'entre execuções recentes',q.failed.length?'bad':'good')}</div>${card('Pull Requests',`<div class="table-wrap"><table><thead><tr><th>PR</th><th>Estado</th><th>Head</th><th>Atualização</th><th></th></tr></thead><tbody>${prs||'<tr><td colspan="5">Nenhum PR aberto</td></tr>'}</tbody></table></div>`,'protected main')}${card('Workflows recentes',`<div class="table-wrap"><table><thead><tr><th>Workflow</th><th>Estado</th><th>Commit</th><th>Atualização</th><th></th></tr></thead><tbody>${runRows||'<tr><td colspan="5">Sem dados</td></tr>'}</tbody></table></div>`,'GitHub Actions')}</div>`}

  function qualityView(){const q=qualityModel(),gates=q.gates.map(g=>`<div class="gate"><div><strong>${esc(g.name)}</strong><span>${esc(g.detail)}</span></div>${pill(g.ok?'PASS':'FAIL',g.ok?'good':'bad')}</div>`).join('');const diagnostics={score:q.score,releaseExact:q.exact,failedRuns:q.failed.length,books:q.books.length,guides:q.guides.length,artifacts:q.artifacts.length,gscCurrent:datasetLabel(state.gsc.current),gscBaseline:datasetLabel(state.gsc.baseline),staged:state.staged.size};return `<div class="stack">${intro('Qualidade & gates','Score explícito, sem “parece bom”. Cada gate tem origem rastreável e o diagnóstico pode ser exportado para auditoria.',pill(`${q.score}/100`,q.score>=90?'good':q.score>=70?'warn':'bad'))}<div class="grid-2">${card('Score operacional',`<div class="quality-summary"><div class="score-ring" style="--score:${q.score}"><div><strong>${q.score}</strong><span>de 100</span></div></div><div class="gate-list">${gates}</div></div>`,'weighted gates')}${card('Diagnóstico resumido',`<pre class="mono" style="white-space:pre-wrap;color:#9aa6b6;font-size:10px;line-height:1.55">${esc(JSON.stringify(diagnostics,null,2))}</pre><button class="btn ghost" data-export-diagnostics>Exportar diagnóstico JSON</button>`,'portable evidence')}</div></div>`}

  function editorView(){const files=(state.tree||[]).filter(x=>x.type==='blob'&&isEditable(x.path)).sort((a,b)=>a.path.localeCompare(b.path));const selected=state.selectedFile;return `<div class="stack">${intro('Editor seguro','Somente arquivos textuais permitidos entram aqui. Workflows, o próprio admin, binários e release.json são bloqueados por política. Arquivos críticos recebem risco elevado no preflight.',pill(`${files.length} arquivos editáveis`))}<section class="card file-browser"><aside class="file-list"><input id="fileSearch" class="search" placeholder="Filtrar arquivos…"><div id="fileItems">${files.slice(0,250).map(f=>`<button class="file-item ${selected?.path===f.path?'active':''}" data-file="${esc(f.path)}" data-search="${esc(normalize(f.path))}"><b>${esc(f.path)}</b><span>${isCritical(f.path)?'CRITICAL':Math.round((f.size||0)/1024)+' KB'}</span></button>`).join('')}</div></aside><div class="editor-pane">${selected?editorPane(selected):'<div class="empty"><strong>Selecione um arquivo</strong><p>O conteúdo será carregado diretamente da main aprovada.</p></div>'}</div></section></div>`}
  function editorPane(f){const staged=state.staged.get(f.path);const content=staged?.content??f.text??'';return `<div class="editor-top"><div class="editor-meta"><strong>${esc(f.path)}</strong><span>${fmt(new TextEncoder().encode(content).length)} bytes · ${fileRisk(f.path).toUpperCase()} risk ${staged?'· STAGED':''}</span></div><div class="small-actions"><button class="mini-btn" data-open-diff="${esc(f.path)}" ${!staged?'disabled':''}>Diff</button>${staged?`<button class="mini-btn" data-unstage="${esc(f.path)}">Remover stage</button>`:''}</div></div>${isCritical(f.path)?'<div class="callout warn" style="margin-bottom:10px"><strong>Arquivo crítico</strong><span>O CI completo deve fechar antes do merge. Evite mudanças simultâneas sem relação causal.</span></div>':''}<textarea id="editorText" class="code-editor" spellcheck="false">${esc(content)}</textarea><div class="dialog-actions"><button class="btn ghost" data-reload-file>Recarregar main</button><button class="btn primary" data-stage-editor>Validar e adicionar ao Change Set</button></div>`}
  async function selectFile(path){try{const f=await ghFile(path);state.selectedFile=f;state.selectedBase=f.text;state.view='editor';render()}catch(e){toast(e.message,'bad')}}
  function validateContent(path,text){const errors=[],warnings=[];if(!isEditable(path))errors.push('caminho bloqueado');if(text.length===0)warnings.push('arquivo vazio');if(path.endsWith('.json')){try{JSON.parse(text)}catch(e){errors.push(`JSON inválido: ${e.message}`)}}if(path.endsWith('.html')){if(!/<title>[^<]+<\/title>/i.test(text))errors.push('HTML sem <title>');if(!/meta\s+name=["']robots["']/i.test(text)&&path.includes('admin/'))warnings.push('HTML administrativo sem robots');if(/googletagmanager\.com|analytics\.tiktok\.com/i.test(text))warnings.push('tracker externo detectado; confirmar consentimento e contrato')}if(path==='robots.txt'&&/disallow:\s*\/\s*$/im.test(text))warnings.push('robots pode bloquear o site inteiro');if(path==='sitemap.xml'&&!/achadostube\.com\.br/i.test(text))errors.push('sitemap não contém domínio canônico');if(path==='monetization.json'){try{const j=JSON.parse(text);if(j.affiliates?.enabled&&!(j.affiliates?.offers||[]).length)errors.push('afiliados ativos sem ofertas');if(j.affiliates?.enabled&&j.guardrails?.affiliateRel!=='sponsored noopener noreferrer')errors.push('affiliateRel fora do guardrail')}catch(_){}}return {errors,warnings}}
  function stageEditor(){if(!state.selectedFile)return;const text=$('#editorText')?.value??'',v=validateContent(state.selectedFile.path,text);if(v.errors.length)return toast(v.errors[0],'bad');stage(state.selectedFile.path,text,state.selectedFile.path,state.selectedBase);if(v.warnings.length)toast(`Staged com aviso: ${v.warnings[0]}`,'warn')}

  function preflight(){const c=config(),max=c.publishing?.maxFilesPerChangeSet||12,items=allStaged(),checks=[];checks.push({ok:items.length>0,level:items.length?'good':'bad',name:'CHANGESET_NONEMPTY',detail:items.length?`${items.length} arquivo(s) em staging`:'nenhuma alteração'});checks.push({ok:items.length<=max,level:items.length<=max?'good':'bad',name:'SCOPE_BUDGET',detail:`${items.length}/${max} arquivos`});for(const x of items){if(x.encoding==='base64'){const ok=binaryPathAllowed(x.path)&&x.bytes>0;checks.push({ok,level:ok?'good':'bad',name:x.path,detail:ok?`${fmt(x.bytes)} bytes · binário validado pelo Book Publisher`:'binário fora da política'});continue}const v=validateContent(x.path,x.content);checks.push({ok:!v.errors.length,level:v.errors.length?'bad':v.warnings.length?'warn':'good',name:x.path,detail:v.errors[0]||v.warnings[0]||'conteúdo passa nas validações locais'})}const critical=items.filter(x=>isCritical(x.path));if(critical.length)checks.push({ok:true,level:'warn',name:'CRITICAL_SURFACE',detail:`${critical.length} superfície(s) crítica(s): ${critical.map(x=>x.path).join(', ')}`});if(!state.token)checks.push({ok:false,level:'bad',name:'WRITE_SESSION',detail:'conecte uma sessão GitHub para publicar'});else checks.push({ok:true,level:'good',name:'WRITE_SESSION',detail:`autorizado como ${state.user?.login||'usuário validado'}`});return checks}
  function changeRisk(){const items=allStaged();if(items.some(x=>fileRisk(x.path)==='high')||items.length>7)return 'high';if(items.some(x=>fileRisk(x.path)==='medium')||items.length>3)return 'medium';return 'low'}
  function changesView(){const items=allStaged(),checks=preflight(),body=items.map(x=>`<div class="change-file"><div><strong>${esc(x.path)}</strong><span>${fmt(x.encoding==='base64'?x.bytes:new TextEncoder().encode(x.content).length)} bytes · ${x.encoding==='base64'?'binário · memória da aba':'texto'} · atualizado ${when(x.updatedAt)}</span></div><div class="small-actions"><span class="risk ${fileRisk(x.path)}">${fileRisk(x.path)}</span><button class="mini-btn" data-open-diff="${esc(x.path)}" ${x.encoding==='base64'?'disabled':''}>Diff</button><button class="mini-btn" data-unstage="${esc(x.path)}">Remover</button></div></div>`).join('');const p=checks.map(x=>`<div class="preflight-row ${x.level}"><i></i><div><strong>${esc(x.name)}</strong><span>${esc(x.detail)}</span></div></div>`).join(''),blocked=checks.some(x=>x.level==='bad');return `<div class="stack">${intro('Change Set','Tudo que será publicado aparece aqui antes do PR. O preflight local complementa — não substitui — os gates do GitHub Actions.',`${pill(`${items.length} arquivo(s)`)} ${pill(`${changeRisk().toUpperCase()} RISK`,changeRisk()==='low'?'good':changeRisk()==='medium'?'warn':'bad')}`)}<div class="grid-2">${card('Alterações',body||'<div class="empty"><strong>Change Set vazio</strong><p>Edite um arquivo ou use uma ação controlada em Monetização.</p></div>','staging restaurável na sessão')}${card('Preflight',`<div class="preflight">${p}</div><div class="dialog-actions"><button class="btn ghost" data-export-changes ${items.length?'':'disabled'}>Exportar backup</button><button class="btn primary" data-open-publish ${blocked?'disabled':''}>Revisar publicação</button></div>`,'antes do PR')}</div></div>`}

  function diffView(path){const x=state.staged.get(path)||state.binaryStaged.get(path);if(!x)return;if(x.encoding==='base64')return toast('Diff binário é revisado por nome, tamanho e hash no PR','warn');$('#diffTitle').textContent=path;const a=String(x.baseContent||'').split('\n'),b=String(x.content||'').split('\n'),max=Math.max(a.length,b.length),out=[];let shown=0;for(let i=0;i<max;i++){if(a[i]===b[i]){if(shown<20&&i<6)out.push(`<div class="diff-line same">  ${esc(a[i]??'')}</div>`);continue}if(a[i]!==undefined)out.push(`<div class="diff-line del">- ${esc(a[i])}</div>`);if(b[i]!==undefined)out.push(`<div class="diff-line add">+ ${esc(b[i])}</div>`);shown++;if(shown>=180){out.push('<div class="diff-line same">… diff truncado no painel; use o PR para revisão completa …</div>');break}}$('#diffBody').innerHTML=out.join('')||'<div class="empty">Sem diferença textual</div>';$('#diffDialog').showModal()}

  function settingsView(){const c=config(),seo=c.seo||{};return `<div class="stack">${intro('Configurações & segurança','A V2 mantém credenciais fora do repositório e não persiste token de escrita. O control-plane versionado contém apenas política pública, thresholds e experimentos — nunca segredos.',pill(state.token?'WRITE SESSION ACTIVE':'READ ONLY',state.token?'blue':'good'))}<div class="grid-2">${card('Sessão GitHub',`<div class="gate-list"><div class="gate"><div><strong>Conta autorizada</strong><span>${esc(c.ownerLogin||OWNER)}</span></div>${pill(state.user?.login||'não conectada',state.token?'good':'')}</div><div class="gate"><div><strong>Persistência de token</strong><span>nenhuma · memória da aba</span></div>${pill('PASS','good')}</div><div class="gate"><div><strong>Main direta</strong><span>proibida pelo publicador</span></div>${pill('PASS','good')}</div></div><div class="dialog-actions"><button class="btn ghost" data-session>${state.token?'Encerrar sessão':'Conectar GitHub'}</button></div>`,'credential boundary')}${card('Política de publicação',`<div class="gate-list"><div class="gate"><div><strong>Branch prefix</strong><span>${esc(c.publishing?.branchPrefix||'control-center/')}</span></div>${pill('PR only','good')}</div><div class="gate"><div><strong>Escopo máximo</strong><span>${fmt(c.publishing?.maxFilesPerChangeSet||12)} arquivos por Change Set</span></div>${pill('budget','blue')}</div><div class="gate"><div><strong>Hashing</strong><span>${esc(c.publishing?.releaseHashing||'sha256')}</span></div>${pill('automatic','good')}</div></div>`,'policy as code')}</div><div class="grid-2">${card('Thresholds SEO',`<pre class="mono" style="white-space:pre-wrap;color:#9aa6b6;font-size:10px">${esc(JSON.stringify(seo,null,2))}</pre>`,'versioned thresholds')}${card('Arquitetura V2',`<div class="callout"><strong>Agora</strong><span>GitHub Pages + GitHub API + GSC CSV local + PR-only publishing + CI.</span></div><div style="height:8px"></div><div class="callout"><strong>Próxima camada</strong><span>Backend privado para OAuth 2.0 do Search Console e credencial GitHub server-side, sem alterar a hospedagem editorial pública.</span></div><div style="margin-top:10px"><button class="btn ghost" data-export-diagnostics>Exportar diagnóstico</button></div>`,'progressive hardening')}</div></div>`}

  function render(){const main=$('#main');if(!main)return;const views={command:commandView,content:contentView,seo:seoView,experiments:experimentsView,money:moneyView,deploy:deployView,quality:qualityView,editor:editorView,changes:changesView,settings:settingsView};main.innerHTML=(views[state.view]||commandView)();const names={command:'Comando',content:'Conteúdo',seo:'SEO Intelligence',experiments:'Experimentos',money:'Monetização',deploy:'Deploy & Releases',quality:'Qualidade',editor:'Editor seguro',changes:'Change Set',settings:'Configurações'};$('#viewTitle').textContent=names[state.view]||state.view;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));updateStagedUi()}
  function setView(v){state.view=v;$('.sidebar').classList.remove('open');render()}

  function parseNumber(v){let s=String(v??'').trim().replace(/\s/g,'').replace('%','');if(!s)return 0;if(s.includes(',')&&s.includes('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
  function detectDelimiter(line){const counts=[',',';','\t'].map(d=>[d,(line.match(new RegExp(d==='\t'?'\\t':`\\${d}`,'g'))||[]).length]);return counts.sort((a,b)=>b[1]-a[1])[0][0]}
  function csvMatrix(text){const delim=detectDelimiter((text.split(/\r?\n/)[0]||''));const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===delim){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(x=>String(x).trim()))}
  function parseGsc(text,fileName){const m=csvMatrix(text);if(m.length<2)throw new Error('CSV sem linhas suficientes');const headers=m[0].map(normalize),idx=(...names)=>{for(const n of names){const i=headers.indexOf(normalize(n));if(i>=0)return i}return -1},qi=idx('query','consulta','consultas'),pi=idx('page','pagina','página','url'),ci=idx('clicks','cliques'),ii=idx('impressions','impressoes','impressões'),cti=idx('ctr'),poi=idx('position','posicao','posição'),di=idx('date','data'),dei=idx('device','dispositivo');if(ci<0||ii<0||cti<0||poi<0)throw new Error('CSV não contém Cliques/Impressões/CTR/Posição');const rows=m.slice(1).map(r=>({query:qi>=0?r[qi]||'':'',page:pi>=0?r[pi]||'':'',clicks:parseNumber(r[ci]),impressions:parseNumber(r[ii]),ctr:parseNumber(r[cti]),position:parseNumber(r[poi]),date:di>=0?r[di]||'':'',device:dei>=0?r[dei]||'':'',key:(qi>=0?r[qi]:pi>=0?r[pi]:'')||''})).filter(r=>r.impressions||r.clicks||r.query||r.page);const dates=rows.map(r=>r.date).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();return {schema:'freedom-gsc-session-v2',fileName,importedAt:new Date().toISOString(),endDate:dates.at(-1)||null,rows}}
  async function importGsc(file,slot){try{const ds=parseGsc(await file.text(),file.name);state.gsc[slot]=ds;sessionStorage.setItem(slot==='current'?SESSION_KEYS.gscCurrent:SESSION_KEYS.gscBaseline,JSON.stringify(ds));toast(`${slot==='current'?'Atual':'Baseline'}: ${fmt(ds.rows.length)} linhas importadas`);render()}catch(e){toast(e.message,'bad')}}
  function clearGsc(){state.gsc={current:null,baseline:null};for(const k of ['current','baseline'])sessionStorage.removeItem(k==='current'?SESSION_KEYS.gscCurrent:SESSION_KEYS.gscBaseline);render();toast('Dados GSC da sessão removidos')}

  function diagnostics(){const q=qualityModel();return {schema:'freedom-control-center-diagnostic-v2',generatedAt:new Date().toISOString(),site:SITE,repository:`${OWNER}/${REPO}`,main:currentBranch(),quality:{score:q.score,gates:q.gates},production:{releaseExact:q.exact,artifactCount:q.artifacts.length},content:{books:q.books.length,guides:q.guides.length},github:{openPullRequests:state.pulls.length,recentFailedRuns:q.failed.length},gsc:{current:state.gsc.current?{label:datasetLabel(state.gsc.current),stats:gscStats(state.gsc.current),rows:state.gsc.current.rows.length}:null,baseline:state.gsc.baseline?{label:datasetLabel(state.gsc.baseline),stats:gscStats(state.gsc.baseline),rows:state.gsc.baseline.rows.length}:null},experiments:(config().experiments||[]).map(x=>{const m=experimentModel(x);return {id:x.id,status:m.status,dataEnd:m.dataEnd,impressions:m.cs.imp}}),changeSet:{files:allStaged().map(x=>x.path),binaryFiles:[...state.binaryStaged.values()].map(x=>({path:x.path,bytes:x.bytes,mime:x.mime})),risk:changeRisk()}}
  }
  function downloadJson(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
  function exportDiagnostics(){downloadJson(`freedom-diagnostic-${new Date().toISOString().slice(0,10)}.json`,diagnostics())}
  function exportChanges(){downloadJson(`freedom-changeset-${new Date().toISOString().replace(/[:.]/g,'-')}.json`,{schema:'freedom-change-set-backup-v2',generatedAt:new Date().toISOString(),base:currentBranch(),files:allStaged().map(x=>x.encoding==='base64'?{path:x.path,encoding:'base64',bytes:x.bytes,mime:x.mime,content:'[memory-only binary omitted]'}:{path:x.path,content:x.content,baseContent:x.baseContent,updatedAt:x.updatedAt})})}

  async function connect(){const token=$('#tokenInput').value.trim(),err=$('#sessionError');err.textContent='';if(!token)return err.textContent='Informe o token.';try{state.token=token;const user=await request(`${GH}/user`);if(user.login!==config().ownerLogin)throw new Error(`Conta ${user.login} não autorizada`);const repo=await request(API);if(!repo.permissions?.push&&!repo.permissions?.admin)throw new Error('Token sem permissão de escrita no repositório');state.user=user;$('#tokenInput').value='';$('#sessionDialog').close();$('#sessionBtn').textContent=user.login;updateStagedUi();toast('Sessão de escrita validada');render()}catch(e){state.token=null;state.user=null;err.textContent=e.message;updateStagedUi()}}
  function disconnect(){state.token=null;state.user=null;$('#sessionBtn').textContent='Modo leitura';updateStagedUi();toast('Sessão de escrita encerrada');render()}
  function showSession(){if(state.token)return disconnect();$('#sessionError').textContent='';$('#sessionDialog').showModal();setTimeout(()=>$('#tokenInput').focus(),50)}

  function patchReleaseHash(text,path,hash){const r=new RegExp(`("${reEsc(path)}"\\s*:\\s*")[a-f0-9]{64}(")`);if(!r.test(text))return text;return text.replace(r,`$1${hash}$2`)}
  async function preparedFiles(){const files=new Map();for(const x of allStaged())files.set(x.path,{...x});const relObj=JSON.parse(state.releaseText||'{"artifacts":{}}');relObj.artifacts=relObj.artifacts||{};let changed=false;for(const [path,x] of files){const bind=x.releaseBound===true||Object.prototype.hasOwnProperty.call(relObj.artifacts,path);if(!bind||x.releaseBound===false)continue;const h=x.encoding==='base64'?await sha256Base64(x.content):await sha256(x.content);if(relObj.artifacts[path]!==h){relObj.artifacts[path]=h;changed=true}}if(changed){const rel=JSON.stringify(relObj,null,2)+'\n';files.set('release.json',{path:'release.json',content:rel,encoding:'utf-8',label:'release hashes automáticos',baseContent:state.releaseText||''})}return files}
  async function showPublish(){if(!state.token)return showSession();const checks=preflight();if(checks.some(x=>x.level==='bad'))return toast('Preflight contém bloqueio','bad');const files=await preparedFiles(),risk=changeRisk();$('#publishSummary').innerHTML=`<div class="metric-grid">${metric('Arquivos',fmt(files.size),stagedCount()===files.size?'sem release adicional':'+ release.json automático')}${metric('Risco',risk.toUpperCase(),'baseado em superfícies tocadas',risk==='low'?'good':risk==='medium'?'warn':'bad')}${metric('Base',short(currentBranch()),'main aprovada')}${metric('Método','PR ONLY','sem escrita direta na main','good')}</div><div style="height:12px"></div><div class="preflight">${checks.map(x=>`<div class="preflight-row ${x.level}"><i></i><div><strong>${esc(x.name)}</strong><span>${esc(x.detail)}</span></div></div>`).join('')}</div>`;$('#publishError').textContent='';$('#publishDialog').showModal()}
  async function createPr(){const err=$('#publishError'),btn=$('#createPrBtn'),title=$('#prTitle').value.trim(),summary=$('#prSummary').value.trim();err.textContent='';if(!title||!summary)return err.textContent='Título e objetivo são obrigatórios.';btn.disabled=true;btn.textContent='Criando PR…';try{
      if(!state.token)throw new Error('Sessão expirada');const files=await preparedFiles();if(files.size>(config().publishing?.maxFilesPerChangeSet||12)+1)throw new Error('Change Set excede orçamento');
      const ref=await request(`${API}/git/ref/heads/main`),baseSha=ref.object.sha,commit=await request(`${API}/git/commits/${baseSha}`),baseTree=commit.tree.sha;
      const slug=normalize(title).replace(/\s+/g,'-').slice(0,38)||'update',branch=`${config().publishing?.branchPrefix||'control-center/'}${new Date().toISOString().slice(0,10)}-${slug}-${Math.random().toString(36).slice(2,6)}`;
      await request(`${API}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/heads/${branch}`,sha:baseSha})});
      const tree=[];for(const [path,x] of files){const blob=await request(`${API}/git/blobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:x.content,encoding:x.encoding||'utf-8'})});tree.push({path,mode:'100644',type:'blob',sha:blob.sha})}
      const newTree=await request(`${API}/git/trees`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:baseTree,tree})});
      const body=`${summary}\n\nChange Set criado pelo Freedom Control Center V2.\n\nArquivos:\n${[...files.keys()].map(x=>`- \`${x}\``).join('\n')}\n\nGuardrails: PR-only · main protegida · release hashes automáticos quando aplicável.`;
      const newCommit=await request(`${API}/git/commits`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:title,tree:newTree.sha,parents:[baseSha]})});
      await request(`${API}/git/refs/heads/${encodePath(branch)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:newCommit.sha,force:false})});
      const pr=await request(`${API}/pulls`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,head:branch,base:'main',body})});
      clearStaged();$('#publishDialog').close();toast(`PR #${pr.number} criado com sucesso`);openUrl(pr.html_url);await sleep(900);await loadAll();setView('deploy');
    }catch(e){err.textContent=e.message;toast(`Falha ao criar PR: ${e.message}`,'bad')}finally{btn.disabled=false;btn.textContent='Criar Pull Request'}}

  globalThis.__FCC_PUBLISHER_API__={
    snapshot:()=>({siteData:clone(state.siteData),tree:clone(state.tree),release:clone(state.release),main:currentBranch(),config:clone(config())}),
    readFile:async(path)=>(await ghFile(path)).text,
    sha256Text:sha256,
    stageBundle:({texts=[],binaries=[]})=>{
      const now=new Date().toISOString(),nextText=[],nextBin=[];
      for(const x of texts){if(!x?.path||typeof x.content!=='string'||!isEditable(x.path)||x.path==='release.json')throw new Error(`Texto gerado fora da política: ${x?.path||'?'}`);nextText.push({...x,encoding:'utf-8',volatile:true,updatedAt:now})}
      for(const x of binaries){if(!x?.path||x.encoding!=='base64'||!binaryPathAllowed(x.path)||!x.content||!x.bytes)throw new Error(`Binário fora da política: ${x?.path||'?'}`);nextBin.push({...x,volatile:true,updatedAt:now})}
      for(const x of nextText)state.staged.set(x.path,x);for(const x of nextBin)state.binaryStaged.set(x.path,x);persistStaged();render();toast(`Bundle editorial: ${texts.length+binaries.length} arquivos no Change Set`);return stagedCount();
    },
    hasPath:(path)=>state.staged.has(path)||state.binaryStaged.has(path),
    openChanges:()=>setView('changes')
  };

  const commands=[
    {name:'Atualizar estado',desc:'Recarregar GitHub, produção e contratos',icon:'↻',run:()=>loadAll()},
    {name:'Publicar novo livro',desc:'Abrir Book Publisher: capa, PDF, landing, SEO e PR',icon:'＋',run:()=>document.dispatchEvent(new CustomEvent('fcc:new-book'))},
    {name:'Ir para SEO Intelligence',desc:'Comparar GSC e oportunidades',icon:'⌁',run:()=>setView('seo')},
    {name:'Ir para Qualidade',desc:'Abrir gates e score operacional',icon:'✓',run:()=>setView('quality')},
    {name:'Abrir Change Set',desc:'Revisar alterações e preflight',icon:'≋',run:()=>setView('changes')},
    {name:'Conectar / encerrar GitHub',desc:'Sessão de escrita somente em memória',icon:'◉',run:()=>showSession()},
    {name:'Exportar diagnóstico',desc:'Gerar evidência JSON local',icon:'⇩',run:()=>exportDiagnostics()},
    {name:'Abrir site público',desc:'achadostube.com.br',icon:'↗',run:()=>openUrl(SITE)}
  ];
  function showCommands(){state.cmdIndex=0;$('#commandSearch').value='';renderCommands();$('#commandDialog').showModal();setTimeout(()=>$('#commandSearch').focus(),40)}
  function filteredCommands(){const q=normalize($('#commandSearch')?.value||'');return commands.filter(x=>!q||normalize(`${x.name} ${x.desc}`).includes(q))}
  function renderCommands(){const xs=filteredCommands();state.cmdIndex=Math.max(0,Math.min(state.cmdIndex,xs.length-1));$('#commandList').innerHTML=xs.map((x,i)=>`<button class="command-item ${i===state.cmdIndex?'selected':''}" data-command="${i}"><i>${esc(x.icon)}</i><div><strong>${esc(x.name)}</strong><span>${esc(x.desc)}</span></div></button>`).join('')||'<div class="empty">Nenhum comando</div>'}
  function runCommand(i){const x=filteredCommands()[i];if(!x)return;$('#commandDialog').close();x.run()}

  if(globalThis.__FCC_TEST_MODE__){globalThis.__FCC_TEST__={parseGsc,opportunityEngine,cannibalization,pdfHtmlConflicts,experimentModel,validateContent,patchReleaseHash,state,config,gscStats,binaryPathAllowed,allStaged};return}

  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-view]');if(nav)return setView(nav.dataset.view);
    const go=e.target.closest('[data-go]');if(go)return setView(go.dataset.go);
    const op=e.target.closest('[data-open]');if(op&&op.dataset.open)return openUrl(op.dataset.open);
    const ed=e.target.closest('[data-edit]');if(ed)return selectFile(ed.dataset.edit);
    const f=e.target.closest('[data-file]');if(f)return selectFile(f.dataset.file);
    const us=e.target.closest('[data-unstage]');if(us)return unstage(us.dataset.unstage);
    const df=e.target.closest('[data-open-diff]');if(df&&!df.disabled)return diffView(df.dataset.openDiff);
    const cl=e.target.closest('[data-close]');if(cl)return $(`#${cl.dataset.close}`).close();
    const mt=e.target.closest('[data-money-toggle]');if(mt)return toggleMoney(mt.dataset.moneyToggle);
    if(e.target.closest('[data-stage-editor]'))return stageEditor();
    if(e.target.closest('[data-reload-file]')&&state.selectedFile)return selectFile(state.selectedFile.path);
    if(e.target.closest('[data-open-publish]'))return showPublish();
    if(e.target.closest('[data-export-diagnostics]'))return exportDiagnostics();
    if(e.target.closest('[data-export-changes]'))return exportChanges();
    if(e.target.closest('[data-clear-gsc]'))return clearGsc();
    if(e.target.closest('[data-session]'))return showSession();
    const cmd=e.target.closest('[data-command]');if(cmd)return runCommand(Number(cmd.dataset.command));
  });
  document.addEventListener('input',e=>{
    if(e.target.id==='contentSearch'){const q=normalize(e.target.value);$$('[data-content-row]').forEach(r=>r.hidden=q&&!r.dataset.search.includes(q))}
    if(e.target.id==='fileSearch'){const q=normalize(e.target.value);$$('[data-file]').forEach(r=>r.hidden=q&&!r.dataset.search.includes(q))}
    if(e.target.id==='commandSearch'){state.cmdIndex=0;renderCommands()}
  });
  document.addEventListener('change',e=>{if(e.target.matches('[data-gsc]')&&e.target.files?.[0])importGsc(e.target.files[0],e.target.dataset.gsc);if(e.target.matches('[data-gsc-end]')){const slot=e.target.dataset.gscEnd;if(state.gsc[slot]){state.gsc[slot].endDate=e.target.value||null;sessionStorage.setItem(slot==='current'?SESSION_KEYS.gscCurrent:SESSION_KEYS.gscBaseline,JSON.stringify(state.gsc[slot]));render()}}});
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showCommands()}if($('#commandDialog')?.open){const xs=filteredCommands();if(e.key==='ArrowDown'){e.preventDefault();state.cmdIndex=Math.min(xs.length-1,state.cmdIndex+1);renderCommands()}if(e.key==='ArrowUp'){e.preventDefault();state.cmdIndex=Math.max(0,state.cmdIndex-1);renderCommands()}if(e.key==='Enter'){e.preventDefault();runCommand(state.cmdIndex)}}});
  $('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
  $('#refreshBtn').addEventListener('click',loadAll);$('#commandBtn').addEventListener('click',showCommands);$('#sessionBtn').addEventListener('click',showSession);$('#publishBtn').addEventListener('click',showPublish);$('#connectBtn').addEventListener('click',connect);$('#createPrBtn').addEventListener('click',createPr);$('#discardAll').addEventListener('click',()=>{clearStaged();$('#publishDialog').close();toast('Change Set descartado','warn')});

  restoreSession();updateStagedUi();
  loadAll().finally(()=>{$('#boot').hidden=true;$('#app').hidden=false;render()});
})();
